/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_exec.h"
#include <string.h>

void
rpc_exec_1(char *host,char *prog,char *args)
{
	CLIENT *clnt;
	int  *result_1;
	in_args  rpc_exec_1_arg;
	strcpy(rpc_exec_1_arg.p_name,prog);
	strcpy(rpc_exec_1_arg.args,args);

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_EXEC, EXEC, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = rpc_exec_1(&rpc_exec_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	int i;
	char *host, prog[50], args[250];

	if (argc < 2) {
		printf ("usage: %s server_host program arguments\n", argv[0]);
		exit (1);
	}
	
	host = argv[1];
	prog = argv[2];
	
	if(argc > 3)
	{
		strcpy(args,argv[3]);
		strcat(args,"~");
		
		if(argc >4)
		{
			for(i = 4; i< argc; i++)
			{
				strcat(args,argv[3]);
				strcat(args,"~");
			}
		}
	}
	else
	{
		strcpy(args,"\0");
	}

	rpc_exec_1 (host,prog,args);
	exit (0);
}
