/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_exec.h"
#include <string.h>

char prog[50],argu[250];
int noa;

void rpc_exec_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	in_args  my_exec_1_arg;
	strcpy(my_exec_1_arg.p_name,prog);
	strcpy(my_exec_1_arg.args,argu);
	my_exec_1_arg.number_of_arguments = noa;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_EXEC, EXEC, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = my_exec_1(&my_exec_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Proces zwrocil: %d\n", result_1);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;
	int i;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	
	host = argv[1];
	
	strcpy(prog,argv[2]);
	noa = ( argc - 3);	
	if(argc > 3)
	{
		strcpy(argu,argv[3]);
		strcat(argu,"~");
		
		if(argc >4)
		{
			for(i = 4; i< argc; i++)
			{
				strcat(argu,argv[i]);
				strcat(argu,"~");
			}
		}
	}
	else
	{
		strcpy(argu,"\0");
	}

	rpc_exec_1 (host);
	exit (0);
}
