/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_exec.h"


void
rpc_exec_1(char *host,char *progname,char *argu)
{
	CLIENT *clnt;
	int  *result_1;
	in_args  rpc_exec_1_arg;

	strcpy(rpc_exec_1_arg.p_name,progname);
	strcpy(rpc_exec_1_arg.args,argu);

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_EXEC, EXEC, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = rpc_exec_1(&rpc_exec_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *progname;
	char *argu;	
	int i;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	progname = argv[2];
	for(i = 3;i <argc;i++)
	{	
		strcat(argu,argv[i]);	
		strcat(argu,"~");
	}
	rpc_exec_1 (host,progname,argu);
	exit (0);
}
