/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_EXEC_H_RPCGEN
#define _RPC_EXEC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct in_args {
	char p_name[50];
	char args[250];
	int number_of_arguments;
};
typedef struct in_args in_args;

#define RPC_EXEC 0x31240055
#define EXEC 1

#if defined(__STDC__) || defined(__cplusplus)
#define MY_EXEC 1
extern  int * my_exec_1(in_args *, CLIENT *);
extern  int * my_exec_1_svc(in_args *, struct svc_req *);
extern int rpc_exec_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MY_EXEC 1
extern  int * my_exec_1();
extern  int * my_exec_1_svc();
extern int rpc_exec_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_in_args (XDR *, in_args*);

#else /* K&R C */
extern bool_t xdr_in_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_EXEC_H_RPCGEN */
