/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_exec.h"
#include <string.h>

char prog[50],argu[250],buff[1024];
int noa,flaga;

void rpc_exec_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	in_args  my_exec_1_arg;
	strcpy(my_exec_1_arg.p_name,prog);
	strcpy(my_exec_1_arg.args,argu);
	my_exec_1_arg.number_of_arguments = noa;
	my_exec_1_arg.flag = flaga;
	strcpy(my_exec_1_arg.buf,buff);

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_EXEC, EXEC, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = my_exec_1(&my_exec_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Proces zwrocil: %d\n", *result_1);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;
	int i,opt;

	if (argc < 2) {
		printf ("usage: %s server_host [-i buff] program arguments\n", argv[0]);
		exit (1);
	}
	
	host = argv[1];
	
	if(strcmp(argv[2],"-i") == 0 )
	{
		flaga = 1;
		strcpy(buff,argv[3]);
		strcpy(prog,argv[4]);
		noa = ( argc - 5);
		opt = 5;
	}
	else
	{	
		flaga = 0;
		strcpy(prog,argv[2]);
		noa = ( argc - 3);	
		opt = 3;
	}

	if(noa)
	{
		strcpy(argu,argv[opt]);
		strcat(argu,"~");
		
		if(argc >(opt+1))
		{
			for(i = (opt + 1); i< argc; i++)
			{
				strcat(argu,argv[i]);
				strcat(argu,"~");
			}
		}
	}
	else
	{
		strcpy(argu,"\0");
	}

	rpc_exec_1 (host);
	exit (0);
}
